# Generated by Django 5.2.17 on 2026-09-24 06:06

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admission", "0004_documentrequirement_applicationdocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectionComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage weight of this component (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "minimum_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "admission_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selection_components",
                        to="admission.admissionperiod",
                    ),
                ),
            ],
            options={
                "db_table": "selection_components",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("room", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=30,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_schedules",
                        to="admission.application",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="selection.selectioncomponent",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_schedules",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "weighted_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="admission.application",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="selection.selectioncomponent",
                    ),
                ),
            ],
            options={
                "db_table": "assessments",
                "ordering": ["-assessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_score", models.DecimalField(decimal_places=4, max_digits=12)),
                ("final_score", models.DecimalField(decimal_places=4, max_digits=12)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_summary",
                        to="admission.application",
                    ),
                ),
            ],
            options={
                "db_table": "application_scores",
                "ordering": ["-final_score", "rank"],
                "indexes": [
                    models.Index(fields=["final_score"], name="ix_app_scores_final"),
                    models.Index(fields=["rank"], name="ix_app_scores_rank"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="selectioncomponent",
            index=models.Index(fields=["admission_period"], name="ix_sel_comp_period_id"),
        ),
        migrations.AddConstraint(
            model_name="selectioncomponent",
            constraint=models.UniqueConstraint(
                fields=("admission_period", "code"), name="uq_selection_comp_period_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="selectioncomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight__gte", Decimal("0.00")), ("weight__lte", Decimal("100.00"))
                ),
                name="ck_selection_comp_weight_range",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentschedule",
            index=models.Index(fields=["application"], name="ix_ass_sched_app_id"),
        ),
        migrations.AddIndex(
            model_name="assessmentschedule",
            index=models.Index(fields=["component"], name="ix_ass_sched_comp_id"),
        ),
        migrations.AddIndex(
            model_name="assessmentschedule",
            index=models.Index(fields=["scheduled_at"], name="ix_ass_sched_time"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["application"], name="ix_ass_app_id"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["component"], name="ix_ass_comp_id"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["assessor"], name="ix_ass_assessor_id"),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("application", "component"), name="uq_assessments_app_component"
            ),
        ),
    ]
