# Generated by Django 5.2.17 on 2026-09-24 06:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0004_documentrequirement_applicationdocument_and_more"),
        ("selection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("WAITLISTED", "Waitlisted"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision",
                        to="admission.application",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decided_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application_decisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DecisionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_decision", models.CharField(max_length=30)),
                ("new_decision", models.CharField(max_length=30)),
                ("reason", models.TextField()),
                (
                    "application_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="selection.applicationdecision",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changed_decision_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decision_histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaitingListEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.IntegerField()),
                ("score", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("PROMOTED", "Promoted"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=30,
                    ),
                ),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_list_entry",
                        to="admission.application",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_waiting_list_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "waiting_list_entries",
                "ordering": ["position", "-score"],
            },
        ),
        migrations.AddIndex(
            model_name="applicationdecision",
            index=models.Index(fields=["decision"], name="ix_app_decision_type"),
        ),
        migrations.AddIndex(
            model_name="applicationdecision",
            index=models.Index(fields=["decided_by"], name="ix_app_decision_by"),
        ),
        migrations.AddIndex(
            model_name="decisionhistory",
            index=models.Index(fields=["application_decision"], name="ix_dec_hist_dec_id"),
        ),
        migrations.AddIndex(
            model_name="decisionhistory",
            index=models.Index(fields=["changed_by"], name="ix_dec_hist_user_id"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["position"], name="ix_wl_pos"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["status"], name="ix_wl_status"),
        ),
    ]
