# Generated by Django 5.2.17 on 2026-09-24 03:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "academic_years",
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lt", models.F("end_date"))),
                        name="ck_academic_years_start_before_end",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_academic_years_single_active",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdmissionPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=100)),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("announcement_at", models.DateTimeField(blank=True, null=True)),
                ("quota", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="admission_periods",
                        to="admission.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "admission_periods",
                "ordering": ["registration_start"],
                "indexes": [
                    models.Index(fields=["academic_year"], name="ix_admission_periods_ay_id")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("registration_start__lt", models.F("registration_end"))
                        ),
                        name="ck_admission_periods_start_before_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quota__isnull", True), ("quota__gte", 0), _connector="OR"
                        ),
                        name="ck_admission_periods_quota_non_negative",
                    ),
                    models.UniqueConstraint(
                        fields=("academic_year", "code"),
                        name="uq_admission_periods_academic_year_code",
                    ),
                ],
            },
        ),
    ]
