# Generated by Django 5.2.17 on 2026-09-24 03:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nisn", models.CharField(blank=True, max_length=20, null=True)),
                ("full_name", models.CharField(max_length=200)),
                ("nickname", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(max_length=20)),
                ("birth_place", models.CharField(max_length=150)),
                ("birth_date", models.DateField()),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                ("nationality", models.CharField(default="Indonesia", max_length=50)),
                ("nik", models.CharField(blank=True, max_length=30, null=True)),
                ("family_card_number", models.CharField(blank=True, max_length=30, null=True)),
                ("address", models.TextField()),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("village", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("previous_school_name", models.CharField(blank=True, max_length=200, null=True)),
                ("previous_school_npsn", models.CharField(blank=True, max_length=30, null=True)),
                ("previous_school_address", models.TextField(blank=True, null=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "applicants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                        ],
                        max_length=30,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("nik", models.CharField(blank=True, max_length=30, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("occupation", models.CharField(blank=True, max_length=150, null=True)),
                ("education", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "monthly_income",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("is_primary_contact", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="admission.applicant",
                    ),
                ),
            ],
            options={
                "db_table": "guardians",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=models.Index(fields=["owner_user"], name="ix_applicants_owner_user_id"),
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(fields=["applicant"], name="ix_guardians_applicant_id"),
        ),
        migrations.AddConstraint(
            model_name="guardian",
            constraint=models.CheckConstraint(
                condition=models.Q(("relationship__in", ["FATHER", "MOTHER", "GUARDIAN"])),
                name="ck_guardians_relationship_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardian",
            constraint=models.UniqueConstraint(
                fields=("applicant", "relationship"), name="uq_guardians_applicant_relationship"
            ),
        ),
    ]
