# Generated by Django 5.2.17 on 2026-09-24 03:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0002_applicant_guardian_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_VERIFICATION", "Under Verification"),
                            ("REVISION_REQUIRED", "Revision Required"),
                            ("RESUBMITTED", "Resubmitted"),
                            ("VERIFIED", "Verified"),
                            ("ASSESSMENT_SCHEDULED", "Assessment Scheduled"),
                            ("ASSESSED", "Assessed"),
                            ("ACCEPTED", "Accepted"),
                            ("WAITLISTED", "Waitlisted"),
                            ("REJECTED", "Rejected"),
                            ("RE_REGISTRATION", "Re-registration"),
                            ("RE_REGISTRATION_VERIFIED", "Re-registration Verified"),
                            ("ENROLLED", "Enrolled"),
                            ("MPLS_ACTIVE", "MPLS Active"),
                            ("MPLS_COMPLETED", "MPLS Completed"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("assessed_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("current_step", models.IntegerField(default=1)),
                ("completion_percentage", models.IntegerField(default=0)),
                (
                    "admission_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="applications",
                        to="admission.admissionperiod",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="admission.applicant",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=50, null=True)),
                ("to_status", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_histories",
                        to="admission.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application_status_histories",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["applicant"], name="ix_applications_applicant_id"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["admission_period"], name="ix_applications_period_id"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="ix_applications_status"),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("applicant", "admission_period"), name="uq_applications_applicant_period"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationstatushistory",
            index=models.Index(fields=["application"], name="ix_app_status_hist_app_id"),
        ),
    ]
