# Generated by Django 5.2.17 on 2026-09-24 05:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0003_application_applicationstatushistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "allowed_mime_types",
                    models.JSONField(
                        default=list,
                        help_text="Allowed MIME types, e.g. ['application/pdf', 'image/jpeg', 'image/png']",
                    ),
                ),
                ("max_file_size_bytes", models.BigIntegerField(default=5242880)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "admission_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="admission.admissionperiod",
                    ),
                ),
            ],
            options={
                "db_table": "document_requirements",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("storage_key", models.TextField()),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("REVISION_REQUIRED", "Revision Required"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="admission.application",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="application_documents",
                        to="admission.documentrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "application_documents",
                "ordering": ["requirement", "-version"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="admission.applicationdocument",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_document_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_revisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentrequirement",
            index=models.Index(fields=["admission_period"], name="ix_doc_req_period_id"),
        ),
        migrations.AddConstraint(
            model_name="documentrequirement",
            constraint=models.UniqueConstraint(
                fields=("admission_period", "code"), name="uq_doc_requirements_period_code"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationdocument",
            index=models.Index(fields=["application"], name="ix_app_docs_app_id"),
        ),
        migrations.AddIndex(
            model_name="applicationdocument",
            index=models.Index(fields=["requirement"], name="ix_app_docs_req_id"),
        ),
        migrations.AddIndex(
            model_name="applicationdocument",
            index=models.Index(fields=["status"], name="ix_app_docs_status"),
        ),
        migrations.AddConstraint(
            model_name="applicationdocument",
            constraint=models.UniqueConstraint(
                fields=("application", "requirement", "version"), name="uq_app_docs_app_req_version"
            ),
        ),
        migrations.AddIndex(
            model_name="documentrevision",
            index=models.Index(fields=["application_document"], name="ix_doc_rev_doc_id"),
        ),
    ]
