# Generated by Django 5.2.17 on 2026-09-24 06:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0004_documentrequirement_applicationdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='re_registration', to='admission.application')),
            ],
            options={
                'db_table': 're_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReRegistrationRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('admission_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_registration_requirements', to='admission.admissionperiod')),
            ],
            options={
                'db_table': 're_registration_requirements',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReRegistrationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('re_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enrollment.reregistration')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enrollment.reregistrationrequirement')),
            ],
            options={
                'db_table': 're_registration_items',
                'ordering': ['requirement__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='reregistration',
            index=models.Index(fields=['status'], name='ix_re_reg_status'),
        ),
        migrations.AddIndex(
            model_name='reregistrationrequirement',
            index=models.Index(fields=['admission_period'], name='ix_re_reg_req_period_id'),
        ),
        migrations.AddConstraint(
            model_name='reregistrationrequirement',
            constraint=models.UniqueConstraint(fields=('admission_period', 'code'), name='uq_re_reg_req_period_code'),
        ),
        migrations.AddIndex(
            model_name='reregistrationitem',
            index=models.Index(fields=['re_registration'], name='ix_re_reg_item_reg_id'),
        ),
        migrations.AddIndex(
            model_name='reregistrationitem',
            index=models.Index(fields=['requirement'], name='ix_re_reg_item_req_id'),
        ),
        migrations.AddConstraint(
            model_name='reregistrationitem',
            constraint=models.UniqueConstraint(fields=('re_registration', 'requirement'), name='uq_re_reg_item_re_reg_req'),
        ),
    ]
